---
title: "Sentimental Analysis of the Trade War with China"
output: html_document
---

```{r, setup, include = FALSE}
library(tidyverse)
library(ggplot2)
library(ggmap)
library(lubridate)
library(rvest)
library(stringr)
library(tidytext)
library(wordcloud)
library(jsonlite)
library(RCurl)
library(XML)
library(RJSONIO)
library(urltools)
options(htmltools.dir.version = FALSE)
```



#NEW YORK TIMES API

##Data Collection
```{r}

#API KEY
key <-"b54a3d8a406247da96456b7bf62ca9ca"

## make path to .Renviron
file <- file.path(path.expand("~"), ".Renviron")

## save environment variable
cat(key, file = file, append = TRUE, fill = TRUE)
```

```{r}
# Tell rtimes what our API key is
Sys.setenv(NYTIMES_AS_KEY = key)
```


```{r}
url <- "http://api.nytimes.com/svc/search/v2/articlesearch.json"
url <- param_set(url, "q", url_encode("Trade War"))
url <- param_set(url, "api-key", url_encode(key))
url <- param_set(url, "page",0)
res1 <- jsonlite::fromJSON(url)

Sys.sleep(1)
url <- param_set(url, "page", 1)
res2 <- jsonlite::fromJSON(url)

Sys.sleep(1)
url <- param_set(url, "page", 2)
res3 <- jsonlite::fromJSON(url)

docs1 <- res1$response$docs
docs2 <- res2$response$docs
docs3 <- res3$response$docs

docs1<-
  docs1%>%
  select(web_url, snippet, lead_paragraph,abstract,pub_date)

docs2<-
  docs1%>%
  select(web_url, snippet, lead_paragraph,abstract,pub_date)

docs3<-
  docs1%>%
  select(web_url, snippet, lead_paragraph,abstract,pub_date)

merged_data<- bind_rows(docs1, docs2, docs3)
merged_data
```

```{r}
dat1<-data.frame(docs1$web_url,docs1$snippet,docs1$lead_paragraph,docs1$pub_date,docs1$headline, docs1$abstract)
dat1
dat2<-
  docs2%>%
  select(web_url, snippet, lead_paragraph, abstract, headline, pub_date)

dat3<-
  docs3%>%
  select(web_url, snippet, lead_paragraph, abstract, headline, pub_date)
```


```{r}
#creating a function to collect all the data from NYtimes API

"nytimes_data<- data.frame()

nytimesfunction<-
  nytimescollector(n, )"
```


```{r}
docs1$keywords
```


  




