---
title: "data_cleaning"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
```

```{r}
data<-read.csv("trade_comm.csv")
```

```{r}
new_data<-data%>%
  mutate(Date= as.Date(Date))%>%
  mutate(Commodity = substr(Commodity,start =3,stop = length(Commodity)))

header.true <- function(df) {
  names(df) <- as.character(unlist(df[1,]))
  df[-1,]
}

hs_code<-read.csv("hs_code.csv")

hs_code1<-header.true(hs_code)

hs_code2<-hs_code1[-1,]

hs_code2
```

```{r}
Live_animals<- hs_code2[1:47,]
library(stringr)



  stuff<-hs_code2%>%
  mutate(number = gsub("[^0-9.]", "",  Date),
         size= nchar(number))%>%
    filter(size ==2| size ==4|size ==5|size==6)

  
  stuff1<-
    stuff%>%
    select(-number)

  
hs_codes<-stuff%>%
  select(Date,number)
names(hs_codes)<- c("Product", "number")

View(hs_codes)


set1<-
  hs_codes%>%
  filter(nchar(number) == 5)%>%
  mutate(hs6 = paste("0",number,sep=""))%>%
  select(Product, hs6)

set2<-
  hs_codes%>%
  filter(nchar(number) == 6)%>%
  mutate(hs6 = number)%>%
  select(Product, hs6)

set1
set2

hs6code<-rbind(set1,set2)

hs6code  

  hs_codes1<-
    hs_codes%>%
  mutate(Commodity = gsub("[!^0-9]"," ",Product))%>%
    select(Commodity, number)
  

  hs_codes1
```

```{r}
names(hs6code)<-c("Date","hs6")
hs6code

as<-
  stuff%>%
  left_join(hs6code)
```


```{r}
as<-as%>%
  select(-Date)


new<-as%>%
  gather(key = Date, value = value, c(-number,-size,-hs6))

new
```

```{r}
#YEARS
unique(new$Date)

important_dates<-new%>%
  group_by(Date)%>%
  summarize(n())%>%
  mutate(nchar = nchar(Date))%>%
  filter(nchar != 4,nchar!=19)

important_dates

important_dates<-important_dates%>%select(Date)

years<- new%>%
  anti_join(important_dates)%>%
  filter(!is.na(hs6))%>%
  mutate(value = ifelse(is.na(value)==TRUE,0,value))
```

```{r}
important_dates

new1<-new%>%
  semi_join(important_dates)

new1

asd<-new1%>%
  separate(Date,into = c("Month","Year"))%>%
  mutate(Month = substr(Month,0,3))%>%
  mutate(Month = match(Month, month.abb))%>%
  mutate(Date = paste("01" ,as.character(Month) ,as.character(Year),sep="/"))%>%
  mutate(Date = as.Date(Date, tryFormats ="%d/%m/%Y"))%>%
  mutate(value = as.numeric(gsub(",","",value)))

asd<-asd%>%
  filter(!is.na(hs6))%>%
  mutate(value = ifelse(is.na(value)==TRUE,0,value))

write.csv(asd,"exports.csv")

write.csv(years,"yearlyexports.csv")

View(asd)
View(years)
```

