---
title: "imports"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)

```


```{r}
exports<-read.csv("exports.csv")

data<-read.csv("imports.csv")
data
data<-data%>%
  mutate(Year = gsub("[^0-9.]", "",  Date))%>%
  mutate(Month = gsub("[^a-zA-Z]", "", Date))

yearly<-
  data%>%
  filter(nchar(Year)==4)

imp<-
  data%>%
  anti_join(yearly)

imp<-imp%>%
  mutate(Month = match(Month,month.abb))%>%
  mutate(Year = (paste("20",Year,sep = "")))%>%
  mutate(Month = as.character(Month))%>%
  mutate(Imports = as.numeric(gsub(",","",Imports)))%>%
  mutate(Date = paste(Year,Month,"01",sep = "-"))%>%
  mutate(Date = as.Date(Date, tryFormats = "%Y-%m-%d"))

exp<-exports%>%
  group_by(Date)%>%
  summarise(exports = sum(value))%>%
  mutate(Date = as.Date(Date))%>%
  mutate(Type = "Exports")

colnames(exp)<-c("Date", "Value", "Type")

exp

imp<-imp%>%select(Date, Imports)%>%
  mutate(Type = "Imports")

colnames(imp)<-c("Date", "Value", "Type")

all<-rbind(exp,imp)

p<-all%>%
  ggplot(aes(x = Date, y = Value, color = Type))+
  geom_line()
```

