---
title: "shinyapp_tariff"
output: html_document
author: "Federico Chung"
---

INPUTS:
country
sector(industry)
-ALL (CATEGORY NEEDED)
product
-ALL (CATEGORY NEEDED)


time

OUTPUT:
Tariff
Exports
Sentiment

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)
library(shiny)
library(shinydashboard)
library(readr)
library(DT)
library(scales)
library(lubridate)
library(plotly)
```

```{r}
CH_tariff<-read.csv("export_tariff_final.csv")
exports<-read.csv("exports.csv")
names<- read.csv("names.csv")

names<-names%>%
  mutate(hs4= ifelse(nchar(hs4)==3,paste("0",hs4,sep="") ,hs4))%>%
  select(hs4, TIER.1.DESCRIPTION)


```


```{r}
CH_tariff<-
  US_tariff%>%
  mutate(Date = as.Date(Date))

Exports<-
  exports%>%
  mutate(Date= as.Date(Date))

Exports<-
  Exports%>%
  select(hs6, value,Date)

Total<-
  Exports%>%
  group_by(Date)%>%
  summarise(value= sum(value))%>%
  mutate(hs6 = "all")%>%
  mutate(hs4 = "all")%>%
  mutate(TIER.1.DESCRIPTION = "all")
Exports
Total<-Total%>%
  select(hs6,value,Date,hs4,TIER.1.DESCRIPTION)



Exports<-Exports%>%
  mutate(hs4 = substr(hs6,start=1,stop=4))


Exports<-Exports%>%
  left_join(names)

Total

exports<-rbind(Exports, Total)
CH_tariff
```



```{r}
#data --> includes all*
exports

#Define a plotting function

plot_exports<- function(product){
  export_data<-
    exports%>%
    filter(TIER.1.DESCRIPTION == product)%>%
    group_by(Date)%>%
    mutate(value = sum(value))
  
  
  p<- ggplot(export_data, aes(x = Date, y = value))+
    geom_line()+
    labs(title = paste("Exports of ",product))
  
  ggplotly(p)
}

plot_tariffs<- function(product){
  EXP_Tariff<-
    CH_tariff%>%
    filter(TIER.1.DESCRIPTION %in% product)%>%
    filter()
  
  p<- ggplot(EXP_Tariff, aes(x = Date, y = effective_tariff_increase, color = Product.Description))+
    geom_step()+
    geom_point()
  
  ggplotly(p)
}

# Build the shiny server
server <- function(input, output) {
  output$plot <- renderPlotly({
    plot_exports(product = input$product)
  })
  
  output$tariffplot<- renderPlotly({
    plot_tariffs(product = input$product)
  })
}

# Build the shiny user interface
ui <- fluidPage(
  radioButtons(
    inputId = "product",
    label = "product",
    choices = unique(exports$TIER.1.DESCRIPTION)
    
    
  ),
  mainPanel(
    h4("Plot:"),
    plotlyOutput("plot"),
    plotlyOutput("tariffplot")
  )
)






# Run the shiny app!
shinyApp(ui = ui, server = server)
```
```{r}
exports

p<-exports%>%
  filter(TIER.1.DESCRIPTION == "all")%>%
  group_by(Date)%>%
  mutate(value = sum(value))%>%
  ggplot(aes(x = Date, y = value))+
  geom_line()

ggplotly(p)

```




```{r}
#Multiple Lines in one graph**


#data --> includes all*
exports

#Define a plotting function

if(interactive()){

plot_exports<- function(product){
  export_data<-
    exports%>%
    filter(TIER.1.DESCRIPTION %in% product)%>%
    group_by(Date,TIER.1.DESCRIPTION)%>%
    mutate(value = sum(value))
  ggplot(export_data, aes(x = Date, y = value, color = product))+
    geom_line()+
    labs(title = paste("Exports of ",product))
}

# Build the shiny server
server <- function(input, output, session) {
  output$plot <- renderPlot({
    plot_exports(product = input$product)
  })
}

# Build the shiny user interface
ui <- fluidPage(
  radioButtons(
    selectizeInput(inputId = "product",
    label = "Select Products:",
    choices = levels(exports$TIER.1.DESCRIPTION)
    
    )
    
    
    
  ),
  mainPanel(
    h4("Plot:"),
    plotOutput("plot")
  )
)

}

# Run the shiny app!
shinyApp(ui = ui, server = server)
```







