---
title: "trade_data_vis"
output: html_document
---

```{r, include = FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
```


```{r}
trade<- read.csv("trade_data_us_china.csv")

trade
```

```{r}
library(anytime)

new_trade<-
  trade%>%
  gather(key = date, value = val, names(trade%>%
                                          select(-c(Commodity))))



new_trade1<-
  new_trade%>%
  separate("date", c("Month","Year"))%>%
  mutate(Month = substr(Month,0,3))%>%
  mutate(Month = match(Month, month.abb))%>%
  mutate(Date = paste("01" ,as.character(Month) ,as.character(Year),sep="/"))%>%
  mutate(Date = as.Date(Date, tryFormats ="%d/%m/%Y"))%>%
  mutate(val = as.numeric(gsub(",","",val)))

LiveAnimals<-
  new_trade%>%
  filter(Commodity == "01 Live Animals")

Total<-
  new_trade1%>%
  group_by(Date)%>%
  summarize(value = sum(val,na.rm = TRUE))

Total
#total amount of exports to china 2015 onwards

```
```{r}
#Trade Visualization
Trade_Vis <- ts(Total$value, start = c(2015,01,01), frequency = 12)

lag(Total$value, 1)
plot(Trade_Vis)
```
```{r}
#Trade Visualization
Trade_Vis <- ts(Total$value, start = c(2015,01,01), frequency = 12)

lag(Total$value, 1)
plot(Trade_Vis)
```


```{r}
#other visualizations

Total_change<-
  Total%>%
  mutate(lag1 = lag(value,1))%>%
  mutate(perc_change = (value - lag1)/value*100)
Total_change

ggplot(Total_change,aes(x = Date, y = perc_change))+
  geom_col()
```
```{r}
#
new_trade1_percchange<-
  new_trade1%>%
  mutate(lag1 = lag(val,98))%>%
  mutate(perc_change = (val - lag1)/val)

new_trade1_percchange
date1<- as.Date("2017-03-31", tryFormats = "%Y-%m-%d")

#add the percentage changes 

study<-
  new_trade1_percchange%>%
  filter(Date> date1)%>%
  group_by(Commodity)%>%
  summarize(change = mean(perc_change))
```
### Expanded Time Frame


```{r}
trade<- read.csv("2002-2019_us_china_trade.csv")
trade_total<- read.csv("2002-2019_us_china_trade_total.csv")
```

```{r}
names(trade)<- c("Time", "Commodity", "val")

trade<-trade%>%
  separate("Time", c("Month","Year"))%>%
  mutate(Month = substr(Month,0,3))%>%
  mutate(Month = match(Month, month.abb))%>%
  mutate(Year = as.numeric(Year) + 2000)%>%
  mutate(Date = paste("01" ,as.character(Month) ,as.character(Year),sep="/"))%>%
  mutate(Date = as.Date(Date, tryFormats ="%d/%m/%Y"))%>%
  mutate(val = as.numeric(gsub(",","",val)))
  
trade<-
  trade%>%
  mutate(Commodity = substr(Commodity,start =3,stop = length(Commodity)))

write.csv(trade,"trade_comm.csv")

Total<-
  trade%>%
  group_by(Date)%>%
  summarize(value = sum(val,na.rm = TRUE))


Total<-Total[-nrow(Total),]
Total
```
```{r}
Trump<- as.Date("2017-03-01")
Trade_Vis <- ts(Total$value, start = c(2002,01,01), frequency = 12)

plot(Trade_Vis)

ggplot(Total, aes(x = Date, y = value))+
  geom_line()+
  geom_vline(xintercept = Trump, color = "red")

trade
```

```
trade%>%
  filter(Commodity=="01 Live Animals")%>%
  ggplot(aes(x = Date, y =val))+
           geom_line()+
  ylim(0,20000000)

trade%>%
  filter(Commodity=="02 Meat And Edible Meat Offal")%>%
  ggplot(aes(x = Date, y =val))+
           geom_line()+
  ylim(0,200000000)

```

```{r}
#withouttradewar\
library(lubridate)
Trump<- as.Date("2017-03-01")

without_war<-
  Total%>%
  filter(Date<Trump)%>%
  mutate(dec_date = decimal_date(Date))

with_war<-
  Total%>%
  filter(Date>Trump)%>%
  mutate(dec_date = decimal_date(Date))
```

```{r}
LOESS <- loess(value ~ dec_date, data = without_war, span = 0.15)

predict(LOESS,newdata = without_war$dec_date)

stuff<-
  Total%>%
  filter(Date<Trump)%>%
  mutate(dec_date = decimal_date(Date))

ggplot(stuff, aes(x = Date, y = value))+
  geom_line()+
  geom_vline(xintercept = Trump, color = "green")+
  geom_line(aes(x = Date, y =LOESS$fitted ), color = "red")


library(forecast)
library(TTR)
ggplot(data = stuff)+
  geom_line(aes(x =dec_date, y= value))+
  geom_line(aes(y = SMA(value,3), x = dec_date), color = "red")

Trade_Vis
export_data_components<- decompose(Trade_Vis)

plot(export_data_components)
```

```{r}
plot(Trade_Vis)
diff1<- diff(Trade_Vis, differences = 1, lag =1)
plot(diff1)


diff2<- diff(export_data_components$random, differences = 1)
plot(diff2)

acf(as.ts(diff2))
```


