---
title: "tariff_visualization"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)
```

```{r}
export_tariff<-read.csv("export_tariff_final.csv")
```

```{r}
export_tariff<-export_tariff%>%
  mutate(hs4= ifelse(nchar(hs4)==3,paste("0",hs4,sep="") ,hs4))
```

```{r}
export_tariff<-export_tariff%>%
  mutate(perc_change_tariff= effective_tariff*100)%>%
  mutate(Date = as.Date(Date))


colnames(export_tariff)<-c("X","hs4","Tariff","imposed_by","Date","effective_tariff_increase","perc_change_tariff")

export_tariff

chn16<-export_tariff%>%
  filter(Tariff == "chn16")%>%
  group_by(hs4)%>%
  summarise(effective_tariff = sum(effective_tariff_increase))%>%
  mutate(Tariff = "chn16")

chn16

chn3<-
  export_tariff%>%
  filter(Tariff == "chn16"|Tariff =="chn3")%>%
  group_by(hs4)%>%
  summarize(effective_tariff = sum(effective_tariff_increase))%>%
  mutate(Tariff = "chn3")


  chn34<-export_tariff%>%
  filter(Tariff == "chn16"|Tariff =="chn3"|Tariff == "chn34")%>%
  group_by(hs4)%>%
  summarize(effective_tariff = sum(effective_tariff_increase))%>%
  mutate(Tariff = "chn34")
  
  chn60b1<-export_tariff%>%
  filter(Tariff == "chn16"|Tariff =="chn3"|Tariff == "chn34"|Tariff =="chn60b1")%>%
  group_by(hs4)%>%
  summarize(effective_tariff = sum(effective_tariff_increase))%>%
  mutate(Tariff = "chn60b1")
  
  chn60b2<-export_tariff%>%
  filter(Tariff == "chn16"|Tariff =="chn3"|
           Tariff == "chn34"|Tariff =="chn60b1"|Tariff=="chn60b2")%>%
  group_by(hs4)%>%
  summarize(effective_tariff = sum(effective_tariff_increase))%>%
  mutate(Tariff = "chn60b2")
  
  chn75b1<-export_tariff%>%
  filter(Tariff == "chn16"|Tariff =="chn3"|
           Tariff == "chn34"|Tariff =="chn60b1"|Tariff=="chn60b2"|
           Tariff == "chn75b1")%>%
  group_by(hs4)%>%
  summarize(effective_tariff = sum(effective_tariff_increase))%>%
  mutate(Tariff = "chn75b1")
  
chn75b2<-export_tariff%>%
  group_by(hs4)%>%
    summarize(effective_tariff = sum(effective_tariff_increase))%>%
    mutate(Tariff = "chn75b2")


a<-rbind(chn16,chn3,chn34,chn60b1,chn60b2,chn75b1,chn75b2)


final<-export_tariff%>%
  left_join(a)

write.csv(final,"final.csv")
```


```{r}
#EFFEctive TARIFF

final%>%
  filter(hs4 =="0101"|hs4 =="0202")%>%
  ggplot(aes(x = Date, y = effective_tariff, color = hs4))+
  geom_point()+
  geom_step()+
  ylim(0,1)
```

```{r}
#PERCENTAGE CHANGE
export_tariff

export_tariff%>%
  filter(hs4 =="0101"|hs4 =="0202")%>%
  ggplot(aes(x = Date, y = perc_change_tariff, color = hs4))+
  geom_point()+
  geom_step()
```

```{r}
hs_index<-
  read.csv("hs_index.csv")

hs_index_1<-hs_index%>%
  filter(Tier == 2)%>%
  select(hs4,Product.Description)%>%
  mutate(hs2= substr(hs4,start=1,stop=2))


colnames(hs_index_2)<-
  c("hs2","TIER 1 DESCRIPTION")


hs_index_1


```

    
```{r}
hs_index_2<-read.csv("hs_index_2.csv")

hs_index_2<-
  hs_index_2%>%
  mutate(hs2 = ifelse(nchar(hs2)==1,paste("0",hs2,sep="") ,hs2))

hs_index_final<-
  hs_index_1%>%
  left_join(hs_index_2)

hs_index_final
```


